### ISSUE TITLE
No bower.json file

### ISSUE THREAD

**Issue by toomu** [foobarbecue/gottafixit#7]
Not all script files are available in the repo. bower.json file is not available either.

**Comment by foobarbecue** [comment]
This software doesn't have a bower.json, because it doesn't use bower. I'd be happy to help if you can be a little more specific about the problem you're having.

**Comment by foobarbecue** [comment]
Sorry about this, working on it now.

**Comment by foobarbecue** [comment]
Fixed in e0d96fdfaa1aedba2c216335fc6996f20f71a65e.
